# Generated by Django 4.2.1 on 2023-05-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.FloatField(default=0.0),
        ),
    ]
